#! /bin/sh
feh --recursive --bg-fill --randomize ~/Downloads/Walpapers/ &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#deadd-notification-center &
dunst &
picom -b --experimental-backends --backend glx
